version: '3.8'

services:
  natures-cafe-postgres:
    image: postgres:latest
    container_name: natures-cafe-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: natures_cafe
    volumes:
      - natures-cafe-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: natures_cafe_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  natures-cafe-data:
